### ISSUE TITLE
Hey, trying to run creddec.py

### ISSUE THREAD

**Issue by I2obiN** [dfirfpi/dpapilab#1]
This is probably a Python issue and I'm being really dumb but I'm trying to get creddec.py to run with Python2.7 and I can't get vaultstruct.py to import

http://i.imgur.com/t31kBjV.png

I have vaultstruct as a folder under Lib and there's a .pyc there too. Sorry if this is a silly issue but I'm just starting out with Python.

**Comment by I2obiN** [comment]
Nvm, working fine

**Comment by dfirfpi** [comment]
Hello @I2obiN, sorry for the late reply... and thanks for the message: happy you solved it!
